# Zola default GH Action
on: push

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main

    - name: Build Site
      run: |
        wget https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz -O zola.tgz
        tar -xvf zola.tgz
        git submodule update --init --recursive
        ./zola build
        cd public
        echo '44yles.dev' > CNAME
        git init
        git config user.name "GitHub Actions"
        git config user.email "github-actions-bot@noreply.github.com"
        git add .
        git commit -m "Deploy ${{ github.repository }} to gh-pages"
        git push --force git@github.com:${{ github.repository }} master:gh-pages

        echo "Deploy complete."
